// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: xmp/common/pagination.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaginationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNumber int64 `protobuf:"zigzag64,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize   int32 `protobuf:"zigzag32,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Total      int64 `protobuf:"zigzag64,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *PaginationMessage) Reset() {
	*x = PaginationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xmp_common_pagination_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationMessage) ProtoMessage() {}

func (x *PaginationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_xmp_common_pagination_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationMessage.ProtoReflect.Descriptor instead.
func (*PaginationMessage) Descriptor() ([]byte, []int) {
	return file_xmp_common_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationMessage) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *PaginationMessage) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationMessage) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_xmp_common_pagination_proto protoreflect.FileDescriptor

var file_xmp_common_pagination_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x78, 0x6d, 0x70, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x78,
	0x6d, 0x70, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x65, 0x0a, 0x11, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x12, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x12, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53,
	0x74, 0x61, 0x73, 0x4a, 0x44, 0x4d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x78, 0x6d, 0x70, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xmp_common_pagination_proto_rawDescOnce sync.Once
	file_xmp_common_pagination_proto_rawDescData = file_xmp_common_pagination_proto_rawDesc
)

func file_xmp_common_pagination_proto_rawDescGZIP() []byte {
	file_xmp_common_pagination_proto_rawDescOnce.Do(func() {
		file_xmp_common_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(file_xmp_common_pagination_proto_rawDescData)
	})
	return file_xmp_common_pagination_proto_rawDescData
}

var file_xmp_common_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xmp_common_pagination_proto_goTypes = []interface{}{
	(*PaginationMessage)(nil), // 0: xmp.common.PaginationMessage
}
var file_xmp_common_pagination_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xmp_common_pagination_proto_init() }
func file_xmp_common_pagination_proto_init() {
	if File_xmp_common_pagination_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xmp_common_pagination_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xmp_common_pagination_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xmp_common_pagination_proto_goTypes,
		DependencyIndexes: file_xmp_common_pagination_proto_depIdxs,
		MessageInfos:      file_xmp_common_pagination_proto_msgTypes,
	}.Build()
	File_xmp_common_pagination_proto = out.File
	file_xmp_common_pagination_proto_rawDesc = nil
	file_xmp_common_pagination_proto_goTypes = nil
	file_xmp_common_pagination_proto_depIdxs = nil
}
